[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyclear"
version = "0.1.0"
description = "A utility package with a clear function"
authors = [{ name = "Tao Ebenezer"}, { email = "2331858952zt@gmail.com"}]